### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by akikanellis**
@dadouf what do you think?

### CODE REVIEW

**Comment by dadouf** [comment]
Sure that jCenter() with capital works?

**Comment by akikanellis** [comment]
I'm not sure what you mean by works. I changed it due to it being written like that on their website.

**Comment by akikanellis** [comment]
I think I see what you mean. You want it to be copy-paste proof?

**Comment by dadouf** [comment]
I meant in a build.gradle file, does it work if you have:

```
repositories {
    jCenter()
}
```

(with a capital)

And actually it doesn't :/ So I would suggest to write in the README:
- either `jcenter()` code-like
- or JCenter simply

**Comment by akikanellis** [comment]
Yep just noticed ^^

**Comment by dadouf** [comment]
:+1:

**Pull request merged**
